version: '3.7'
services:
  db:
    image: postgres:11.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  deploy:
    build: infra/
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=ap-northeast-1
      - KUBECONFIG=/workspace/k8s/.kube/config
    volumes:
      - .:/workspace/rails
      - ./infra/k8s:/workspace/k8s
      - ./infra/terraform:/workspace/terraform
    privileged: true
