version: '3.7'
services:
  db:
    image: postgres:11.6
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
  web:
    build: server/
    volumes:
      - ./server:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
  deploy:
    build: infra/
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=ap-northeast-1
      - KUBECONFIG=/workspace/k8s/.kube/config
    volumes:
      - ./server:/workspace/server
      - ./infra/k8s:/workspace/k8s
      - ./infra/terraform:/workspace/terraform
    privileged: true
